Add pix
starkinfra/sdk-elixir pull request #2
Opened 2022-05-11 17:04 UTC by AdryanAlencar

2022-05-17 14:17 UTC, massaru-stark requested changes

2022-05-17 14:17 UTC, massaru-stark commented on CHANGELOG.md
> +### Added 2022-05-02
- Está diferente do padrão do CHANGELOG dos outros SDKs. A gente só coloca a data no dia da release.

- PixDirection também é só para participantes diretos

```
## [Unreleased]
### Added
- CreditNote resource for money lending with Stark Infra's endorsement
- PixRequest resource for Indirect and Direct Participants
- PixReversal resource for Indirect and Direct Participants
- PixDirector resource for Direct Participants
- PixBalance resource for Indirect and Direct Participants
- PixStatement resource for Direct Participants
- PixClaim resource for Indirect and Direct Participants
- PixKey resource for Indirect and Direct Participants
```

2022-05-17 14:17 UTC, massaru-stark commented on README.md
>      - [CreditNote](#create-creditnotes): Create credit notes
Precisa criar uma parte só pra CreditNote
```
- [Credit Note](#credit-note)
    - [CreditNote](#create-creditnotes): Create credit notes
```

2022-05-17 14:17 UTC, massaru-stark commented on README.md
>      - [CreditNote](#create-creditnotes): Create credit notes
Tem que colocar isso lá embaixo no conteúdo também

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +    sender_name: "Cora Pagamentos Ltda.",
É uma boa trocar esses exemplos, coloca os mesmos que estão no README de python

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +    end_to_end_id: StarkInfra.EndToEndID.generate("35547753")
Coloca ou um endToEndId fixo ou deixa explícito que ele tem que colocar o ISPB dele aí nesse generate()

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +
Pode tirar essa linha em branco (vale pra todos os outros lugares que tiver assim!)

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +  after: Date.utc_today |> Date.add(-30),
Adiciona os outros parâmetros que estão no exemplo de python

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +request = StarkInfra.PixRequest.get!("pix_request_id") |> IO.inspect
Coloca um ID aleatório aqui:
```elixir
request = StarkInfra.PixRequest.get!("5155165527080960") |> IO.inspect
```

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +request = StarkInfra.PixRequest.get!("pix_request_id") |> IO.inspect
Mesma coisa para os outros exemplos de get()

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +
Falta adicionar o exemplo de `Process inbound PixRequest authorizations`

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +      end_to_end_id: "end_to_end_id",
Adicionar um exemplo de endToendId e externalId
- externalId: 17238435823958934
- endToEndId: E00000000202201060100rzsJzG9PzMg

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +  ) |> Enum.take(10) |> IO.inspect
Adiciona os outros parâmetros de exemplo, copia o de python!
Mesma coisa para todos os outros exemplos com parâmetros

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +  logs = StarkInfra.PixRequest.Log.query(
Pode tirar essa indentação

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +  log = StarkInfra.PixRequest.Log.get!("log_id") |> IO.inspect
Indentação de novo, pode tirar de todos que tiverem assim!

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +  ) |> IO.inspect
No python a gente adicionou alguns comentários pra auxiliar o usuário, pode colocar aqui também?
```python
import starkinfra

statement = starkinfra.pixstatement.create(
    starkinfra.PixStatement(
        after="2022-01-01", # This is the date that you want to create a statement.
        before="2022-01-01", # After and before must be the same date.
        type="transaction" # Options are "interchange", "interchangeTotal", "transaction".
    )
)

print(statement)
```

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +  statement_csv = StarkInfra.PixStatement.get_csv!("statement_id") |> IO.inspect
Imagino que o exemplo para csv não seja assim, talvez da mesma maneira que o PDF de Invoice do sdk de bank:
```elixir
pdf = StarkBank.Invoice.pdf!("6750458353811456", layout: "default")

file = File.open!("invoice.pdf", [:write])
IO.binwrite(file, pdf)
File.close(file)
```

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +      tax_id: "34.052.649/0001-78",
Bom trocar esses exemplos

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +    sender_name: "Cora Pagamentos Ltda.",
O mesmo vale para todos os outros exemplos

2022-05-17 14:17 UTC, massaru-stark commented on README.md
> +
Falta exemplo de PixDirector

2022-05-17 14:17 UTC, massaru-stark commented on CHANGELOG.md
> +### Added 2022-05-02
Falta implementar:
- PixInfraction
- PixChargeback
- PixDomain

2022-05-17 14:17 UTC, massaru-stark commented on lib/credit_note/credit_note.ex
>      defstruct [
Nas docstrings, pode tirar o default dos atributos que são return-only!

2022-05-17 14:17 UTC, massaru-stark commented on lib/pix_balance/pix_balance.ex
> +    @moduledoc """
Começo da docstring está diferente do bank, exemplo:
```  
  @moduledoc """
  Groups Invoice related functions
  """

  @doc """
  When you initialize a Invoice struct, the entity will not be automatically
  sent to the Stark Bank API. The 'create' function sends the structs...
  """
```

2022-05-17 14:17 UTC, massaru-stark commented on lib/credit_note/credit_note.ex
>      defstruct [
Adiciona o Signer pra CreditNote, já está implementado no sdk-python

2022-05-17 14:17 UTC, massaru-stark commented on lib/pix_balance/pix_balance.ex
> +        - `:updated` [DateTime , default nil]: latest update DateTime for the PixBalance. ex:  ~U[2020-3-10 10:30:0:0]
Tem espaço a mais aqui no meio:
`ex:  ~U[2020-3-10 10:30:0:0]`

2022-05-17 14:17 UTC, massaru-stark commented on lib/pix_balance/pix_balance.ex
> +            updated: json[:updated]
Precisa adicionar a validação de datetime

2022-05-17 14:17 UTC, massaru-stark commented on lib/pix_balance/pix_balance.ex
> +        - `:id` [binary, default nil]: unique id returned when Balance is created. ex: "5656565656565656"
Type de id é `string`

2022-05-17 14:17 UTC, massaru-stark commented on lib/pix_balance/pix_balance.ex
> +        - `:currency` [binary, default nil]: currency of the current Workspace. Expect others to be added eventually. ex: "BRL"
Type de currency é `string`

2022-05-17 14:17 UTC, massaru-stark commented on lib/pix_balance/pix_balance.ex
> +        - `:user` [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkinfra.user was set before function call
Faz um replace all dessas linhas de user por
```
- `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.
```

2022-05-17 14:17 UTC, massaru-stark commented on lib/pix_balance/pix_balance.ex
> +
Pode retirar essa linha em branco!

2022-05-17 18:38 UTC, massaru-stark requested changes

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim.ex
> +        - `:account_created` [Date, DateTime or binary]: opening Date or DateTime for the account claiming the PixKey. ex: "2022-01-01".
Tem que arrumar todos esses types `binary`

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim.ex
> +        - `:id` [binary, default nil]: unique id returned when the PixClaim is created. ex: "5656565656565656"
Pode tirar o default de todos os return-only, faz a mesma coisa em todos os outros arquivos também!

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim.ex
> +    ## Parameters (optional):
Aqui é `## Parameters (required):`

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim.ex
> +        - `:key_type` [binary, default nil]: filter for the PixKey type of retrieved PixClaims. Options: "cpf", "cnpj", "phone", "email" and "evp",
Trocar para:
`Options: "cpf", "cnpj", "phone", "email", "evp".`

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim.ex
> +        - `:key_type` [binary, default nil]: filter for the PixKey type of retrieved PixClaims. Options: "cpf", "cnpj", "phone", "email" and "evp",
Mesma coisa no page

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim.ex
> +        Receive a generator of PixClaims structs previously created in the Stark Infra API
Essa é a descrição de query() atualiza pra de page.
Exemplo de python, adequa pra elixir:
```
Receive a list of up to 100 PixClaims objects previously created in the Stark Infra API and the cursor to the next page.
Use this function instead of query if you want to manually page your requests.
```

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_balance/pix_balance.ex
> +            updated: json[:updated]
Faz isso pra todos outros lugares também

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim.ex
> +        - `:id` [binary]: PixClaim id. ex: '5656565656565656'
Troca o apóstrofo por aspas

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim.ex
> +        binary,
Coloca o type na mesma linha do nome do parâmetro

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim_log.ex
> +        - `:created` [DateTime.t()]: creation datetime for the log. ex:  ~U[2020-3-10 10:30:0:0]
Pode tirar esse .t()

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim_log.ex
> +        - `:created` [DateTime.t()]: creation datetime for the log. ex:  ~U[2020-3-10 10:30:0:0]
Espaço duplo entre : e ~

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim_log.ex
> +        - `:after` [Date.t() or binary, default nil]: date filter for structs created after specified date. ex: ~D[2020, 3, 10]
[Date or string, default nil]

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim_log.ex
> +        - `:after` [Date.t() or binary, default nil]: date filter for structs created after specified date. ex: ~D[2020, 3, 10]
Mesma coisa para todos outros lugares

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim_log.ex
> +        - `:created` [DateTime.t()]: creation datetime for the log. ex:  ~U[2020-3-10 10:30:0:0]
Arrumar em todos os outros lugares, faz o replace all 😃

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_claim/pix_claim_log.ex
> +        - `:ids` [list of binarys, default nil]: Log ids to filter PixClaim Logs. ex: ["5656565656565656"]
plural de binary é binaries, mas muda pra list of strings 😂

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_key/pix_key.ex
> +        user: Project.t() | Organization.t() | nil
Falta adicionar o  end_to_end_id aqui e no get!()

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_key/pix_key.ex
> +        {:halt, any} |
O que é isso? kkkk

2022-05-17 18:38 UTC, massaru-stark commented on lib/pix_key/pix_key.ex
> +            owned: json[:owned],
owned e account_created também precisam de validação de datetime

2022-05-17 19:42 UTC, AdryanAlencar commented on lib/pix_claim/pix_claim_log.ex
> +        - `:ids` [list of binarys, default nil]: Log ids to filter PixClaim Logs. ex: ["5656565656565656"]
famoso replace all

2022-05-17 20:14 UTC, massaru-stark requested changes

2022-05-17 20:14 UTC, massaru-stark commented on lib/pix_request/pix_request.ex
> +        - `:requests [list of PixRequest structs]: list of PixRequest structs to be created in the API
Em todos os parâmetros desse arquivo está faltando o ` depois do nome do parâmetro

2022-05-17 20:14 UTC, massaru-stark commented on lib/pix_request/pix_request.ex
> +        - `:list of PixRequest structs with updated attributes
Aqui não tem esse `:

2022-05-17 20:14 UTC, massaru-stark commented on lib/pix_request/pix_request.ex
> +        - `:list of PixRequest structs with updated attributes
Mesma coisa nos próximos Returns

2022-05-17 20:14 UTC, massaru-stark commented on lib/pix_reversal/pix_reversal.ex
> +            tags: json[:tags],
Coloca esse tags entre o id e o return_id pra ficar no padrão de required -> optional -> required-only

2022-05-17 20:14 UTC, massaru-stark commented on lib/pix_statement/pix_statement.ex
> +        - `:transaction_count` [integer, default nil]: number of transactions that happened during the day that the PixStatement was requested. ex 11
ex: 11

2022-05-17 20:14 UTC, massaru-stark commented on lib/pix_statement/pix_statement.ex
> +            "pix_statements",
PixStatement

2022-05-17 20:14 UTC, massaru-stark commented on lib/utils/end_to_end_id.ex
> +        for _ <- 1..length, into: "", do: <<Enum.random('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWYZ')>>
Troca para ' para "

2022-05-17 20:14 UTC, massaru-stark commented on lib/utils/end_to_end_id.ex
> +defmodule StarkInfra.EndToEndID do
Renomear o módulo para EndToEndId

2022-05-17 20:14 UTC, massaru-stark commented on mix.lock
> +}
Certeza que precisa commitar isso?

2022-05-17 20:14 UTC, massaru-stark commented on test/credit_note_test.exs
> +        credit_note = StarkInfra.CreditNote.query!(limit: 2, status: "created")
Aqui não é teste de create e delete?

2022-05-17 20:14 UTC, massaru-stark commented on test/credit_note_test.exs
> +        credit_note = StarkInfra.CreditNote.query!(limit: 2, status: "created")
Aqui não é teste de create e delete?

2022-05-17 20:14 UTC, massaru-stark commented on test/credit_note_test.exs
> +            template_id: "5707012469948416",
Não deixa isso hardcoded, coloca no utils.user.
Copia do python

2022-05-17 20:14 UTC, massaru-stark commented on test/credit_note_test.exs
Tem um enter a mais

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_claim_log_test.exs
> +            StarkInfra.PixClaim.Log.query!()
Coloca o filtro de limit=1 pra não ter que pegar 100, dado que você só pega o primeiro que retornar

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_claim_log_test.exs
> +            StarkInfra.PixClaim.Log.query!()
Mesma coisa para os outros testes

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_claim_log_test.exs
> +        |> (fn list -> assert length(list) == 1 end).()
No caso desse teste, acho que faz mais sentido tirar o limit=1 da query e comparar o id de cada PixClaim dos logs retornados com o pix_claim.id passado no filtro

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_claim_log_test.exs
> +        {:ok, ids} = StarkInfraTest.Utils.Page.get(&StarkInfra.PixClaim.Log.page/1, 2, limit: 5)
Usa o named parameters nos primeiros dois parâmetros pra facilitar a leitura

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_claim_test.exs
> +            key_id: "+5511933571793",
Cria um método pra criar um número aleatório, pode copiar o de Python

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_claim_test.exs
> +end
Adicionar linha em branco ao final do file

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_director_test.exs
> +end
Remover os enters a mais e adicionar uma linha em branco no final do arquivo

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_director_test.exs
> +        }
Coloca uma aleatoriedade nos campos

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_claim_log_test.exs
> +        |> (fn list -> assert length(list) == 1 end).()
Mesma coisa pros testes de busca de logs com filtros dos outros arquivos

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_key_log_test.exs
> +
Tirar enter a mais

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_key_test.exs
> +        {:ok, key} = StarkInfra.PixKey.get(pix_key.id, payer_id: "012.345.678-90")
Cria um TaxIdGenerator.taxId() pra esse caso

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_key_test.exs
> +            |> Enum.each(fn {:ok, pix_key} -> StarkInfra.PixKey.delete(pix_key.id) end)
A descrição do teste não condiz com o que está sendo feito

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_key_test.exs
> +end
Retirar linha em branco acima e adicionar uma em branco no final do arquivo

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_key_test.exs
> +    end
Faz esse método gerar dados aleatórios

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_key_test.exs
> +end
Mesma coisa pra todos os outros arquivos de teste

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_request_test.exs
> +            end_to_end_id: StarkInfra.EndToEndID.generate("35547753")
Adicionar aleatoriedade na geração do exemplo

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_reversal_log_test.exs
> +        assert length(ids) == 4
Isso aqui deve quebrar, o length retornado pode ser 10

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_reversal_log_test.exs
> +        assert length(ids) == 4
Mesma coisa nos testes abaixo e de outros arquivos

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_reversal_test.exs
> +    # get end-to-end-id from pix request where pix flow is "in"
Não precisa desse comentário
- pra facilitar, pode renomear essa cadeia de métodos para get_end_to_end_id_to_reverse

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_reversal_test.exs
> +            external_id: "euibgfquikq2222e232242u1vy232rjkqef",
Coloca uma aleatoriedade nesse external_id, no python a gente usa uuid4

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_statement_test.exs
> +
Faltou testar query(), page() e get()

2022-05-17 20:14 UTC, massaru-stark commented on test/pix_statement_test.exs
> +        }
Adiciona a aleatoriedade pro type entre "interchange", "interchangeTotal" e "transaction"

2022-05-17 20:14 UTC, massaru-stark commented on test/test_helper.exs
> +    #:pix_claim_log
Pode deixar descomentado

2022-05-27 14:03 UTC, joaogpw-stark commented on README.md
> +  status: "success",
Da um check se não quebra porque era pra ser lista

2022-05-27 14:03 UTC, joaogpw-stark commented on README.md
> +StarkInfra.PixRequest.create([
Ta sem bang!, em quase todas ta sem

2022-05-27 14:03 UTC, joaogpw-stark commented on README.md
> +log = StarkInfra.PixRequest.Log.get!("123312313") |> IO.inspect
Id zuado aqui

2022-05-27 14:03 UTC, joaogpw-stark commented on README.md
> +reversal = StarkInfra.PixReversal.get!("reversal_id") |> IO.inspect
Isso ta fora do padrão, reversal_id

2022-05-27 14:03 UTC, joaogpw-stark commented on README.md
> +You can query pix request logs to better understand pix request life cycles.
pix -> Pix

2022-05-27 14:03 UTC, joaogpw-stark commented on README.md
> +  after: Date.utc_today |> Date.add(-30), # This is the date that you want to create a statement.
Aqui o after e o before tem que ser o mesmo dia

2022-05-27 14:03 UTC, joaogpw-stark commented on README.md
> +file = File.open!("statement.csv", [:write])
Aqui é um cdv, mas vem um .zip

2022-05-27 14:03 UTC, joaogpw-stark commented on README.md
> +key = StarkInfra.PixKey.create([
PostSingle

2022-05-27 14:03 UTC, joaogpw-stark commented on README.md
> +key = StarkInfra.PixKey.get!("key_id", payer_id: "012.345.678-90") |> IO.inspect
"key_id",

2022-05-27 14:03 UTC, joaogpw-stark commented on lib/credit_note/credit_note_log.ex
> +    ) :: any
Aqui não tem any -> any?

2022-05-27 14:03 UTC, joaogpw-stark commented on lib/pix_reversal/pix_reversal_log.ex
> +    {:ok, [Log.t()]} |
identaçao

2022-05-27 14:03 UTC, joaogpw-stark commented on lib/utils/bacen_id.ex
> +
Linha vazia a mais

2022-05-27 14:31 UTC, joaogpw-stark approved these changes

2022-05-27 14:32 UTC, merged