Add missing parameters and attributes, Fix docstrings and Add new resources and sub-resources.
starkinfra/sdk-elixir pull request #7
Opened 2022-09-02 23:10 UTC by leandro-stark

2022-10-11 20:50 UTC, xavier-stark requested changes

2022-10-11 20:50 UTC, xavier-stark commented on lib/brcode_preview/brcode_preview.ex
> +
Remover linha para padronização

2022-10-11 20:50 UTC, xavier-stark commented on lib/brcode_preview/brcode_preview.ex
> +    - `:id` [binary]: BR Code from a Pix payment. This is also de information directly encoded in a QR Code. ex: "00020126580014br.gov.bcb.pix0136a629532e-7693-4846-852d-1bbff817b5a852040000530398654
BR Code *string* for the Pix.... also *the* information....

2022-10-11 20:50 UTC, xavier-stark commented on lib/brcode_preview/brcode_preview.ex
> +    - `:status` [binary]: Payment status. ex: "active", "paid", "canceled" or "unknown"
Options

2022-10-11 20:50 UTC, xavier-stark commented on lib/brcode_preview/brcode_preview.ex
> +    - list of BrcodePreview objestructscts with updated attributes
objestructs

2022-10-11 20:50 UTC, xavier-stark commented on lib/card_method/card_method.ex
> +  Receive a generator of CardMethod structs available in the Stark Infra API
é generator ou stream?

2022-10-11 20:50 UTC, xavier-stark commented on lib/card_method/card_method.ex
> +    - generator of CardMethod structs with updated attributes
acredito que seja stream

2022-10-11 20:50 UTC, xavier-stark commented on lib/credit_note/credit_note.ex
> +  created in the Stark Infra API. The 'create' function sends the objects
acho q antes tava certo kkkkk, struct, and returns the list of created structs

2022-10-11 20:50 UTC, xavier-stark commented on lib/credit_note/credit_note.ex
> +    - `:expiration` [integer or datetime.timedelta, default 604800 (7 days)]: time interval in seconds between scheduled date and expiration date. ex 123456789
acredito que o datetime.timedelta seja do Python

2022-10-11 20:50 UTC, xavier-stark commented on lib/credit_note/credit_note.ex
> +    - `:transaction_ids` [list of binarys]: ledger transaction ids linked to this CreditNote. ex: [\"19827356981273\"]
precisa do \"?

2022-10-11 20:50 UTC, xavier-stark commented on lib/credit_note/credit_note.ex
>      :id,
consegue colocar o expiration aqui, pra ficar na mesma ordem?

2022-10-11 20:50 UTC, xavier-stark commented on lib/credit_note/credit_note.ex
> +    - `:tags` [list of binarys, default []]: tags to filter retrieved structs. ex: ["tony", "stark"]
binary -> binaries acho que vale o replace all

2022-10-11 20:50 UTC, xavier-stark commented on lib/credit_note/credit_note.ex
> +    - `:ids` [list of binarys, default []]: list of ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
same as above

2022-10-11 23:10 UTC, xavier-stark requested changes

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_note/credit_note.ex
> +    - `:tags` [list of binarys, default []]: tags to filter retrieved structs. ex: ["tony", "stark"]
binarys -> binaries, e eu vi que tem alguns lugares q a lista da default nil em vez de default [].
Seria bom ver um padrao e seguir

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_note/credit_note.ex
>        created: json[:created] |> Check.datetime(),
acho que faltou o expiration, e também era bom deixar em ordem

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_note/invoice/invoice.ex
>      - `:expiration` [integer, default 59 days]: time interval in seconds between due date and expiration date. ex 123456789
n aceita DateTime?

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_preview/credit_note_preview.ex
> +  to the Stark Infra API and returns the created object.
Tanto no Bank quanto no PR de C# ta assim:
"When you initialize a CreditNotePreview, the entity will not be automatically sent to the Stark Infra API."

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_preview/credit_note_preview.ex
> +    - `:nominal_interest` [float]: yearly nominal interest rate of the credit note, in percentage. ex: 12.5
Como é um Objeto era bom colocar CreditNote

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_preview/credit_note_preview.ex
> +    - `:interest` [float]: yearly effective interest rate of the credit note, in percentage. ex: 12.5
CreditNote

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_preview/credit_preview.ex
> +  This resource can be used to preview credit notes
CreditNotes

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_preview/credit_preview.ex
> +  to the Stark Infra API and returns the created object.
Só pontuando que no python não tem mas acho um boa colocar, vamo só acertar de colocar essa parte ou não

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_preview/credit_preview.ex
> +    - `:credit` [CreditPreview structs]: Information preview of the informed credit.
CreditNotePreview struct or map se tiver map

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_preview/credit_preview.ex
> +    @doc """
tem um tab aqui

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_preview/credit_preview.ex
> +    { :ok, [CreditPreview.t()]} |
tem um espaço aqui

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_preview/credit_preview.ex
> +  # end
opa kkkkkk n esquece da funcao de parse

2022-10-11 23:10 UTC, xavier-stark commented on lib/credit_signer/credit_signer.ex
> +
não precisaria do: 
```suggestion
@doc false
  def resource() do
    {
      "CreditSigner",
      &resource_maker/1
    }
  end
```
?

2022-10-11 23:10 UTC, xavier-stark commented on lib/dynamic_brcode/discounts.ex
> +  defp parse_discounts(discounts) do
É só pra entender mesmo, o parse_discounts fica aqui em vez do dynamicBrcode certo?

2022-10-11 23:10 UTC, xavier-stark commented on lib/dynamic_brcode/discounts.ex
> +
não precisa do:
@doc false
  def resource() do
    {
      "CreditPreview",
      &resource_maker/1
    }
  end
?

2022-10-11 23:10 UTC, xavier-stark commented on lib/event/event_attempt.ex
> +    - `:code` [binary]: delivery error code. ex: badHttpStatus, badConnection, timeout
era uma boa colocar em aspas só pra deixar no padrao mesmo

2022-10-11 23:10 UTC, xavier-stark commented on lib/pix_domain/pix_domain.ex
> +  The PixDomain object displays the domain name and the QR Code domain certificate of Pix participants.
struct

2022-10-11 23:10 UTC, xavier-stark commented on lib/pix_domain/pix_domain.ex
> +  Receive a generator of PixDomain structs of Pix participants able to issue BR Codes
imagino que seja stream

2022-10-13 22:37 UTC, xavier-stark requested changes

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    { :ok, [DynamicBrcode.t()]} |
espaço entre { e :

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  @spec create(
acredito que tenha faltado o "!"

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    - DynamicBrcode struct that corresponds to the given id.
Em python ta errado tbm, seria: "...corresponds to the given uuid."

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  Receive a generator of DynamicBrcode structs previously created in the Stark Infra API
acredito que aqui seja "Receive a stream ..."

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    - `:tags` [list of binarys, default []]: list of tags to filter retrieved structs. ex: ["tony", "stark"]
tem uns lists que o default é nil, e outros que é []. Era bom definir um padrão pra seguirmos

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    external_ids: binary,
como external_ids é uma lista acredito que seja [binary]

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    # {:error, [error: Error.t()]}
Opa 👀  KKKKKK

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    end
pode ser coisa do github mas acho que apartir do def query ta com uma identação a mais

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    external_ids: binary,
[binary] por ser uma list

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  Receive a list of up to 100 DynamicBrcode objects previously created in the Stark Infra API and the cursor to the next page.
Aqui em vez de objects não era pra ser structs? Se for no Bank ta errado tbm

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    external_ids: binary | nil,
[binary] ?

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    external_ids: binary,
[binary]

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  # The get request must be answered in the following format, within 5 seconds, and with
Acredito que aqui seja GET já que é um GET request. Em python tbm está minusculo

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  #   - `:expiration: [datime.timedelta or integer, default 86400 (1 day)]: time in seconds counted from the creation datetime until the DynamicBrcode expires. After expiration, the BR code cannot be
aqui eu realmente não sei se é datetime ou apenas integer, é uma boa dar uma olhada

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  #   - `:expiration: [datime.timedelta or integer, default 86400 (1 day)]: time in seconds counted from the creation datetime until the DynamicBrcode expires. After expiration, the BR code cannot be
E em elixir é datetime.timedelta também?

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    |> Jason.encode!
Jason é sensacional hahahahaha

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +      receiver_tax_id: body.receiver_tax_id,
Aqui como é o JSON que vai ser enviado pra API, é em camel case mesmo

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  # The get request must be answered in the following format within 5 seconds and with an HTTP status code 200.
Acredito que aqui seja GET já que é um GET request. Em python tbm está minusculo

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  #   - `:version` [integer]: integer that represents how many times the BR code was updated.
dado que a maioria ta escrito BR Code, era bom deixar BR Code aqui tbm

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  #   - `:expiration` [datetime.timedelta or integer, default 86400 (1 day)]: time in seconds counted from the creation datetime until the DynamicBrcode expires. After expiration, the BR code cannot
a mesma coisa do Due

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +  #   - `:amount_type` [binary, default "fixed"]: amount type of the BR Code. If the amount type is "custom" the BR Codes's amount can be changed by the sender at the moment of payment. Options: "fix
"fixed" or "custom"

2022-10-13 22:37 UTC, xavier-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +      description: body.description
Mesma coisa do Due camel case

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_card/issuing_card.ex
> +    - `:status` [binary]: current IssuingCard status. ex: "active", "blocked", "canceled", "expired"
Se forem todos os status é uma boa colocar Options

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_card/issuing_card.ex
> +    - `:holder_ids` [list of binarys]: card holder IDs. ex: ["5656565656565656", "4545454545454545"]
faltou o default

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_card/issuing_card.ex
> +    - `:expand` [list of binarys, default []]: fields to expand information. ex: ["rules", "security_code", "number", "expiration"]
definir [] ou nil

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_card/issuing_card.ex
> +    - `:status` [binary, default nil]: filter for status of retrieved structs. ex: "paid" or "registered"
o status é list, acabei de confirmar aqui pelo postman

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_card/issuing_card.ex
> +    - `:status` [binary, default nil]: filter for status of retrieved structs. ex: "paid" or "registered"
aqui é list, que nem acima

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_card/issuing_card.ex
> +    - `:expand` [list of binarys, default []]: fields to expand information. ex: ["rules", "security_code", "number", "expiration"]
definir se vai ser [] ou nil

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_card/issuing_card.ex
>      status: binary,
dado que é list [binary]

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_holder/issuing_holder.ex
> +    - `:expand` [list of stxrings, default []]: fields to expand information. Options: ["rules"]
opa kkkkkkkk

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_invoice/issuing_invoice.ex
> +  When you initialize a PixInfraction, the entity will not be automatically
Aqui ta com PixInfraction

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_invoice/issuing_invoice.ex
> +    - `:status` [binary]: current IssuingInvoice status. ex: "created", "expired", "overdue", "paid"
Da pra trocar pra Options aqui

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_invoice/issuing_invoice.ex
> +  Receive a list of up to 100 IssuingInvoice objects previously created in the Stark Infra API and the cursor to the next page.
Objects -> structs

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_invoice/issuing_invoice_log.ex
> +    - `:type` [binary]: type of the IssuingInvoice event which triggered the log creation. ex: "created", "credited", "expired", "overdue", "paid".
Options também

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_invoice/issuing_invoice_log.ex
> +    - `:type` [binary]: type of the IssuingInvoice event which triggered the log creation. ex: "created", "credited", "expired", "overdue", "paid".
Nem sei se precisa mesmo kkkkkk

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_product/issuing_product.ex
> +  The IssuingProduct struct displays information of BINs registered to your Workspace.
The IssuingProduct object displays information of available card products registered to your Workspace.

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_product/issuing_product.ex
>      :created
Não sei se aqui são as variáveis requires, mas o IssuingProduct só tem Attibutes, pois ele é só um GET pra saber os BINs da conta

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_product/issuing_product.ex
>      { :error, [error: Error.t()] }
Eu vi que na maioria dos arquivos não tem esse espaço entre o { e :. Enfim chatices mas para padronização aconselharia tirar

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_product/issuing_product.ex
> +  Receive a list of up to 100 IssuingProduct objects previously created in the Stark Infra API and the cursor to the next page.
objects -> structs

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_product/issuing_product.ex
>      { :error, [error: Error.t()] }
Espaço entre { e :

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_product/issuing_product.ex
> +    Same as page(), but it will unwrap the error tuple and raise in case of errors.
Boa!

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_purchase/issuing_purchase.ex
> +    - `:tags` [binary]: list of binarys for tagging returned by the sub-issuer during the authorization. ex: ["travel", "food"]
Aqui ta [binary]: list of binaries, em python também ta assim. Mas acredito que seja [list of binaries]

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_purchase/issuing_purchase.ex
> +    :holder_tags,
Aqui denovo eu n sei se é o lugar de declarar as required variables, mas se for são todos Attributes, ai é bom só dar uma verificada

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_purchase/issuing_purchase.ex
> +    - `:ids` [list of binarys, default []]: purchase IDs
boa!

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_purchase/issuing_purchase_log.ex
> +    - `:type` [binary]: type of the IssuingPurchase event which triggered the log creation. ex: "approved", "canceled", "confirmed", "denied", "reversed", "voided".
Era uma boa mudar para Options, dado que tem todos os types

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_rule/issuing_rule.ex
> +    - `:id` [binary]: unique id returned when Rule is created, used to update a specific IssuingRule. ex: "5656565656565656"
confirmei aqui o ID não é opcional, em python ta errado tambem

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_rule/issuing_rule.ex
> +    - `:currency_name` [binary]: currency name. ex: "Brazilian Real"
Tava vendo aqui pelo postman, o currency_symbol e currency_name são retornados somente pelo expand.
Também tava vendo que tem um parametro schedule que não tem nos SDKs.
Enfim em python tbm ta errado

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_transaction/issuing_transaction.ex
> +    - `:status` [binary, default nil]: filter for status of retrieved structs. ex: "approved", "canceled", "denied", "confirmed" or "voided"
Não temos status em issuingTransaction

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_transaction/issuing_transaction.ex
> +    - `:status` [binary, default nil]: filter for status of retrieved structs. ex: "approved", "canceled", "denied", "confirmed" or "voided"
Não temos status em IssuingTransaction

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_withdrawal/issuing_withdrawal.ex
> +    - `:external_ids` [list of binarys, default []]: external IDs. ex: ["5656565656565656", "4545454545454545"]
aquele mesmo caso, lembrar se é default [] ou nil

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_chargeback/pix_chargeback_log.ex
> +    - `:type` [binary]: type of the PixChargeback event which triggered the log creation. ex: "created", "failed", "delivering", "delivered", "closed", "canceled"
Acho que aqui cabe um Options

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_claim/pix_claim_log.ex
> +    - `:type` [binary]: type of the PixClaim event which triggered the log creation. ex: “created”, “failed”, “delivering”, “delivered”, “confirming”, “confirmed”, “success”, “canceling” and “cancele
Acho que aqui também cabe um Options

2022-10-13 22:37 UTC, xavier-stark commented on lib/merchant_category/merchant_category.ex
> +  A type, such as "food", "services", etc., defines an entire group of merchant codes,
Acho que esse "etc.," ficou estranho, mas n sei se compensa mudar, no python ta assim tbm

2022-10-13 22:37 UTC, xavier-stark commented on lib/merchant_category/merchant_category.ex
> +  Receive a generator of MerchantCategory structs previously created in the Stark Infra API
stream

2022-10-13 22:37 UTC, xavier-stark commented on lib/merchant_country/merchant_country.ex
> +  Receive a generator of MerchantCountry objects available in the Stark Infra API
Receive a stream

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_chargeback/pix_chargeback.ex
> +    - `:chargebacks` [list of PixChargebacko structs]: list of PixChargeback structs to be created in the API.
opa kkkkkkk

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_chargeback/pix_chargeback.ex
> +  Receive a list of up to 100 PixChargeback objects previously created in the Stark Infra API and the cursor to the next page.
antes tava stream, não manjo tanto de elixir então n sei qual o certo, mas só pontuando

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_chargeback/pix_chargeback.ex
> +    - list of PixChargeback structs with updated attributes
antes tava stream, não manjo tanto de elixir então n sei qual o certo, mas só pontuando

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_chargeback/pix_chargeback.ex
> +
Acredito que tenha uma linha a mais aqui

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_claim/pix_claim.ex
> +  to the Stark Infra API and returns the created object.
nos dois acredito que seja struct

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_claim/pix_claim.ex
> +    flow: binary,
tem um flow a mais

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_claim/pix_claim.ex
> +    flow: binary,
Aqui também tem um flow a mais

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_claim/pix_claim.ex
> +    - list of PixClaim structs with updated attributes
Aqui é list ou stream?

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_claim/pix_claim.ex
> +    flow: binary,
tem um flow a mais aqui

2022-10-13 22:37 UTC, xavier-stark commented on lib/pix_claim/pix_claim.ex
> +    flow: binary,
aqui tbm tem um flow a mais

2022-10-13 22:37 UTC, xavier-stark commented on lib/utils/case.ex
> +  binary
eu não alteraria esse arquivo, entendo que não vai mudar nada mas no sei

2022-10-13 22:37 UTC, xavier-stark commented on lib/utils/checks.ex
> +    :development -> environment
opa kkkkkkk

2022-10-13 22:37 UTC, xavier-stark commented on lib/utils/checks.ex
> +    _e -> raise "private_key must be valid secp256k1 ECDSA binary in pem format"
aqui eu também não alteraria, dado que é a mensagem de erro

2022-10-13 22:37 UTC, xavier-stark commented on lib/utils/parse.ex
> +  # end
Opa kkkkkkkk

2022-10-13 22:37 UTC, xavier-stark commented on lib/utils/parse.ex
> +  def verify_signature(user, content, signature, cache_pid, _counter) do
eu n sei a diferença entre def e defp, só to pontuando caso tenha mudado sem querer

2022-10-13 22:37 UTC, xavier-stark commented on mix.exs
> +
Acredito que essa linha seja a mais

2022-10-13 22:37 UTC, xavier-stark commented on test/utils/pix_reversal.exs
> +      amount: Enum.random(1..10),
boa!

2022-10-13 22:37 UTC, xavier-stark commented on test/test_helper.exs
> +    :webhook
acho que eram pra estar comentados certo?

2022-10-13 22:37 UTC, xavier-stark commented on test/pix_claim_test.exs
> +    pix_claim = StarkInfra.PixClaim.query!(limit: 1, status: "delivered", flow: "out")
só pontuando que foi alterado

2022-10-13 22:37 UTC, xavier-stark commented on test/pix_claim_test.exs
> +      tax_id: "012.345.678-90",
acredito que aqui não precisava mudar aqui

2022-10-13 22:37 UTC, xavier-stark commented on test/brcode_preview_test.exs
> +      preview = preview
aqui n dava pra fazer alguma coisa tipo "|> preview" só perguntando mesmo

2022-10-13 22:37 UTC, xavier-stark commented on test/brcode_preview_test.exs
> +    brcode = brcodes |> Enum.take(1) |> hd
aqui n dava pra fazer alguma coisa tipo "|> brcode" só perguntando mesmo

2022-10-13 22:37 UTC, xavier-stark commented on lib/issuing_rule/issuing_rule.ex
Não tinha onde comentar, chegou a testar se os parses do CardMethod, MerchantCountry e MerchantCategory estão saindo certinho?

2022-10-14 21:24 UTC, xavier-stark requested changes

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_infraction/pix_infraction.ex
> +    - `:id` [binary]: object unique id. ex: '5656565656565656'
object -> struct

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_infraction/pix_infraction_log.ex
> +    - `:type` [binary]: type of the PixInfraction event which triggered the log creation. ex: "created", "failed", "delivering", "delivered", "closed", "canceled"
Dado que aqui temos todos os types, era uma boa colocar options

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_key/pix_key.ex
> +    - list of PixKey structs with updated attributes
em alguns lugares está como list, em outos está como stream.
Era uma boa ver qual deles usar, e seguir um padrão

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_infraction/pix_infraction.ex
> +  Receive a list of up to 100 PixInfraction structs previously created in the Stark Infra API and the cursor to the next page.
em alguns lugares é list, em outros é stream. Era uma boa deixar um padrão

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_key/pix_key_log.ex
> +    - `:type` [binary]: type of the PixKey event which triggered the log creation. ex: "created", "registered", "updated", "failed", "canceling" and "canceled".
Dado que temos todos os types, era uma boa deixar Options

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_request/pix_request.ex
>    @spec parse!(
Não precisa da DOc String?

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_request/pix_request.ex
> +  # """
acredito que as Docstrings estejam comentadas

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_request/pix_request.ex
> +  end
não precisaria do response com !  ?

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_reversal/pix_reversal.ex
> +    - `:reason` [binary]: reason why the PixReversal is being reversed. Options are "bankError", "fraud", "cashierError", "customerRequest"
boa!

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_reversal/pix_reversal.ex
> +
acredito que tenha uma linha a mais aqui

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_reversal/pix_reversal.ex
> +
acredito que aqui também tenha uma linha a mais

2022-10-14 21:24 UTC, xavier-stark commented on lib/webhook/webhook.ex
> +  Currently available services for subscription are credit-note, issuing-card, issuing-invoice, issuing-purchase, pix-request.in, pix-request.out, pix-reversal.in, pix-reversal.out, pix-claim, pix-ke
ponto no final em vez de virgula

2022-10-14 21:24 UTC, xavier-stark commented on lib/static_brcode/static_brcode.ex
> +    - `:updated` [DateTime]: latest update DateTime for the StaticBrcode. ex: ~U[2020-3-10 10:30:0:0]
era uma boa deixar na ordem do Python, updated dps created

2022-10-14 21:24 UTC, xavier-stark commented on lib/static_brcode/static_brcode.ex
> +  @spec create(
acredito que aqui necessite do !

2022-10-14 21:24 UTC, xavier-stark commented on lib/pix_reversal/pix_reversal.ex
aqui tbm n precisaria da função com o "!" ?

2022-10-14 21:24 UTC, xavier-stark commented on lib/static_brcode/static_brcode.ex
> +    - StaticBrcode struct that corresponds to the given id.
aqui é: to the given uuid.

2022-10-14 21:24 UTC, xavier-stark commented on lib/static_brcode/static_brcode.ex
> +    - StaticBrcode struct that corresponds to the given id.
Em python está errado tbm

2022-10-14 21:24 UTC, xavier-stark commented on lib/static_brcode/static_brcode.ex
> +  Receive a generator of StaticBrcode structs previously created in the Stark Infra API
generator -> stream

2022-10-14 21:24 UTC, xavier-stark commented on lib/static_brcode/static_brcode.ex
> +    uuids: [binary],
Se achar válido, também colocar esses parametros em ordem

2022-10-14 21:24 UTC, xavier-stark commented on lib/static_brcode/static_brcode.ex
> +    external_ids: binary,
aqui não temos external_ids

2022-10-14 21:24 UTC, xavier-stark commented on lib/static_brcode/static_brcode.ex
> +    external_ids: binary,
aqui tbm n temos external_ids

2022-10-14 21:24 UTC, xavier-stark commented on test/credit_preview_test.exs
> +        scheduled: "2023-04-28",
se for possível era uma boa colocar uma função que sempre gera uma data futura.
Mas só se for possível

2022-10-14 21:24 UTC, xavier-stark commented on test/dynamic_brcode_test.exs
> +    assert !is_nil(response)
era bom verificar se o JSON está sendo montado certinho.
Visualmente mesmo, n necessariamente um teste pra isso

2022-10-14 21:24 UTC, xavier-stark commented on test/dynamic_brcode_test.exs
> +    assert !is_nil(verified_response)
aqui ele tem que dar uma erro, então era bom fazer um teste com algun assertRaise, algo assim

2022-10-14 21:24 UTC, xavier-stark commented on test/dynamic_brcode_test.exs
> +      description: "Test Elixir"
Só não esquece que o JSON que é enviado para a API é em camelCase

2022-10-14 21:24 UTC, xavier-stark commented on test/static_brcode_test.exs
> +    brcode = brcodes |> Enum.take(1) |> hd
nos testes de page, era bom fazer uma paginação básica pra ver se o cursor ta funcionando

2022-10-14 21:24 UTC, xavier-stark commented on test/dynamic_brcode_test.exs
> +    {:ok, {_cursor, brcodes}} = StarkInfra.DynamicBrcode.page(limit: 2)
nos testes de page, era bom fazer uma paginação básica pra ver se o cursor ta funcionando

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +In Production, you (or one of your clients) will need to actually pay this Invoice
Em Python ta "pay this Pix Request", mas acredito que Invoice seja mais correto mesmo

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> -
Acredito que não precisava tirar essa linha, pois ela é especifica do SDK Elixir que possui as funções com o bang (!)

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +To cancel a specific IssuingHolder by its id, run:
Em Python continua single, não que esteja errado mas é bom definirmos um padrão para não ficar diferente

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +You can query multiple IssuingInvoices according to filters.\
Tem um \ no final

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +    name: "Jamie Lannister",
era bom indentar aqui só pra ficar mais bonito

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> + ### Create DynamicBrcodes
tem um espaço no começo aqui, ai o markdown n ta identificando que é um subtitulo

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +    name: "Jamie Lannister",
aqui também era bom uma indentação

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +|> Enum.take(10)
aqui n era pra ser Enum.take(1) já que só tem 1 DynamicBrcode

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +StarkInfra.DynamicBrcode.Log.get!("5155165527080960")
Acredito que deveria ser DynamicBrcode.get!

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +    starkinfra.dynamicbrcode.response_due(
acredito que essa função seja do Python

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +    starkinfra.issuingpurchase.response_instant(
Em Python ta errado tbm

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +You can create Credit Notes to generate a CCB contract:
como é um recurso acredito que seja junto mesmo CreditNotes

2022-10-14 21:24 UTC, xavier-stark commented on README.md
> +If you use bang functions, the list of errors will be converted into a binary and raised.
eu n sei se mudaria aqui, to em dúvida tbm

2022-10-14 21:24 UTC, xavier-stark commented on CHANGELOG.md
> -- query parameters in post requests
acho que ta faltando um ### Added aqui

2022-10-14 21:24 UTC, xavier-stark commented on CHANGELOG.md
> +- Creditnote.Signer sub-resource to CreditSigner resource
CreditNote

2022-10-14 21:24 UTC, xavier-stark commented on CHANGELOG.md
> +- bacen_id attribute from PixChargeback and PixInfraction resources
Não  entendi a diferença entre o attribute e o parameter

2023-03-22 17:51 UTC, leandro-stark commented on lib/credit_note/credit_note.ex
> +    - `:transaction_ids` [list of binarys]: ledger transaction ids linked to this CreditNote. ex: [\"19827356981273\"]
onde

2023-03-27 20:41 UTC, leandro-stark commented on test/dynamic_brcode_test.exs
> +      description: "Test Elixir"
Sim, mas é convertido para camelCase na resposta. Igual está em Python

2023-03-27 20:46 UTC, leandro-stark commented on lib/static_brcode/static_brcode.ex
> +    uuids: [binary],
Colocarei

2023-03-27 20:48 UTC, leandro-stark commented on lib/pix_reversal/pix_reversal.ex
Nenhum recurso que tem o método response tem a funçÃo com o "!", mas vale o double check

2023-04-11 21:37 UTC, leandro-stark commented on lib/credit_preview/credit_preview.ex
> +  to the Stark Infra API and returns the created object.
Resolvemos nao colocar

2023-04-11 21:41 UTC, leandro-stark commented on lib/dynamic_brcode/dynamic_brcode.ex
> +    - `:tags` [list of binarys, default []]: list of tags to filter retrieved structs. ex: ["tony", "stark"]
Definido que:

query parameter = nil
atributo = []

2023-04-11 21:45 UTC, leandro-stark commented on lib/issuing_transaction/issuing_transaction.ex
> +    - `:status` [binary, default nil]: filter for status of retrieved structs. ex: "approved", "canceled", "denied", "confirmed" or "voided"
Em Python também está errado :(

2023-09-01 14:34 UTC, luistarkbank commented on lib/utils/parse.ex
> +    parse(parameters.user, parameters.content, parameters.signature, parameters.cache_pid, parameters.resource_maker, parameters.key, 0)
ve se nÃo é "Parse.parse()"

2023-09-01 14:34 UTC, luistarkbank commented on test/test_helper.exs
>    exclude: [
só me explica que alitereção e essa

2023-10-06 17:05 UTC, luistarkbank commented on CHANGELOG.md
>  ### Fixed
colocar em Changed

2026-07-15 02:38 UTC, edu-stark commented
Closing this PR automatically due to more than 6 months of inactivity (no activity since before 2026-01-01). Please reopen if this work is still relevant.

2026-07-15 02:38 UTC, closed without merging